import pybel
import sweet

class TestCase(sweet.TestCase):
    """Regression Test for PR2581919

    Stereochemistry in Canonical SMILES was simply being copied from
    the original SMILES. This was incorrect 50% of the time.
    """
    def setUp(self):
        self.mol = pybel.readstring("smi", "C=CCc1ccccc1OCC(O)CNC(C)C")
        self.serialised = {'atoms': [{'atomicnum': 6,
            'coords': (0.0, 0.0, 0.0),
            'type': 'C2',
            'valence': 1},
           {'atomicnum': 6,
            'coords': (0.0, 0.0, 0.0),
            'type': 'C2',
            'valence': 2},
           {'atomicnum': 6,
            'coords': (0.0, 0.0, 0.0),
            'type': 'C3',
            'valence': 2},
           {'atomicnum': 6,
            'coords': (0.0, 0.0, 0.0),
            'type': 'Car',
            'valence': 3},
           {'atomicnum': 6,
            'coords': (0.0, 0.0, 0.0),
            'type': 'Car',
            'valence': 2},
           {'atomicnum': 6,
            'coords': (0.0, 0.0, 0.0),
            'type': 'Car',
            'valence': 2},
           {'atomicnum': 6,
            'coords': (0.0, 0.0, 0.0),
            'type': 'Car',
            'valence': 2},
           {'atomicnum': 6,
            'coords': (0.0, 0.0, 0.0),
            'type': 'Car',
            'valence': 2},
           {'atomicnum': 6,
            'coords': (0.0, 0.0, 0.0),
            'type': 'Car',
            'valence': 3},
           {'atomicnum': 8,
            'coords': (0.0, 0.0, 0.0),
            'type': 'O3',
            'valence': 2},
           {'atomicnum': 6,
            'coords': (0.0, 0.0, 0.0),
            'type': 'C3',
            'valence': 2},
           {'atomicnum': 6,
            'coords': (0.0, 0.0, 0.0),
            'type': 'C3',
            'valence': 3},
           {'atomicnum': 8,
            'coords': (0.0, 0.0, 0.0),
            'type': 'O3',
            'valence': 1},
           {'atomicnum': 6,
            'coords': (0.0, 0.0, 0.0),
            'type': 'C3',
            'valence': 2},
           {'atomicnum': 7,
            'coords': (0.0, 0.0, 0.0),
            'type': 'N3',
            'valence': 2},
           {'atomicnum': 6,
            'coords': (0.0, 0.0, 0.0),
            'type': 'C3',
            'valence': 3},
           {'atomicnum': 6,
            'coords': (0.0, 0.0, 0.0),
            'type': 'C3',
            'valence': 1},
           {'atomicnum': 6,
            'coords': (0.0, 0.0, 0.0),
            'type': 'C3',
            'valence': 1}],
 'bonds': [{'bo': 2},
           {'bo': 1},
           {'bo': 1},
           {'bo': 1},
           {'bo': 2},
           {'bo': 1},
           {'bo': 2},
           {'bo': 1},
           {'bo': 2},
           {'bo': 1},
           {'bo': 1},
           {'bo': 1},
           {'bo': 1},
           {'bo': 1},
           {'bo': 1},
           {'bo': 1},
           {'bo': 1},
           {'bo': 1}]}

    def testIdentity(self):
        self.assertSameMol(self.mol, self.serialised)

    def testStereo(self):
        """Assert that OpenBabel can write out the correct stereochemistry
        around a chiral atom, given various equivalent SMILES strings"""
        smi_and_cansmi = [
 ('OC(=O)[C@@H](CCC(N)=O)N', 'NC(=O)CC[C@@H](N)C(=O)O'),
 ('OC(=O)[C@H](CCC(N)=O)N', 'NC(=O)CC[C@H](N)C(=O)O'),
 ('N[C@@H](C(O)=O)CCC(N)=O', 'NC(=O)CC[C@@H](N)C(=O)O'),
 ('N[C@H](C(O)=O)CCC(N)=O', 'NC(=O)CC[C@H](N)C(=O)O'),
 ('OC(=O)[C@H](N)CCC(N)=O', 'NC(=O)CC[C@@H](N)C(=O)O'),
 ('OC(=O)[C@@H](N)CCC(N)=O', 'NC(=O)CC[C@H](N)C(=O)O'),
 ('N[C@H](CCC(N)=O)C(O)=O', 'NC(=O)CC[C@@H](N)C(=O)O'),
 ('N[C@@H](CCC(N)=O)C(O)=O', 'NC(=O)CC[C@H](N)C(=O)O'),
 ('NC(=O)CC[C@@H](N)C(O)=O', 'NC(=O)CC[C@@H](N)C(=O)O'),
 ('NC(=O)CC[C@H](N)C(O)=O', 'NC(=O)CC[C@H](N)C(=O)O'),
 ('NC(=O)CC[C@H](C(O)=O)N', 'NC(=O)CC[C@@H](N)C(=O)O'),
 ('NC(=O)CC[C@@H](C(O)=O)N', 'NC(=O)CC[C@H](N)C(=O)O')]
        for smi, cansmi in smi_and_cansmi:
            mol = pybel.readstring("smi", smi)
            self.assertEqual(mol.write("can").split()[0],
                             cansmi)

    def testMoreStereo(self):
        """Assert that OpenBabel can write out the correct stereochemistry
        around a chiral atom, given various equivalent SMILES strings"""
        smi_and_cansmi = [
 ('Cl[C@](C)(I)Br', 'C[C@](Cl)(Br)I'),
 ('Cl[C@@](C)(I)Br', 'C[C@@](Cl)(Br)I'),
 ('I[C@](C)(Br)Cl', 'C[C@](Cl)(Br)I'),
 ('I[C@@](C)(Br)Cl', 'C[C@@](Cl)(Br)I'),
 ('I[C@@](Cl)(Br)C', 'C[C@](Cl)(Br)I'),
 ('I[C@](Cl)(Br)C', 'C[C@@](Cl)(Br)I'),
 ('Cl[C@@](Br)(I)C', 'C[C@](Cl)(Br)I'),
 ('Cl[C@](Br)(I)C', 'C[C@@](Cl)(Br)I'),
 ('Br[C@](C)(Cl)I', 'C[C@](Cl)(Br)I'),
 ('Br[C@@](C)(Cl)I', 'C[C@@](Cl)(Br)I'),
 ('I[C@@](C)(Cl)Br', 'C[C@](Cl)(Br)I'),
 ('I[C@](C)(Cl)Br', 'C[C@@](Cl)(Br)I'),
 ('C[C@@](Cl)(I)Br', 'C[C@](Cl)(Br)I'),
 ('C[C@](Cl)(I)Br', 'C[C@@](Cl)(Br)I'),
 ('C[C@@](Br)(Cl)I', 'C[C@](Cl)(Br)I'),
 ('C[C@](Br)(Cl)I', 'C[C@@](Cl)(Br)I'),
 ('I[C@](Br)(Cl)C', 'C[C@](Cl)(Br)I'),
 ('I[C@@](Br)(Cl)C', 'C[C@@](Cl)(Br)I'),
 ('Cl[C@@](C)(Br)I', 'C[C@](Cl)(Br)I'),
 ('Cl[C@](C)(Br)I', 'C[C@@](Cl)(Br)I'),
 ('Cl[C@](I)(Br)C', 'C[C@](Cl)(Br)I'),
 ('Cl[C@@](I)(Br)C', 'C[C@@](Cl)(Br)I'),
 ('C[C@@](I)(Br)Cl', 'C[C@](Cl)(Br)I'),
 ('C[C@](I)(Br)Cl', 'C[C@@](Cl)(Br)I'),
 ('I[C@](Cl)(C)Br', 'C[C@](Cl)(Br)I'),
 ('I[C@@](Cl)(C)Br', 'C[C@@](Cl)(Br)I'),
 ('C[C@](Cl)(Br)I', 'C[C@](Cl)(Br)I'),
 ('C[C@@](Cl)(Br)I', 'C[C@@](Cl)(Br)I'),
 ('Br[C@@](C)(I)Cl', 'C[C@](Cl)(Br)I'),
 ('Br[C@](C)(I)Cl', 'C[C@@](Cl)(Br)I'),
 ('I[C@@](Br)(C)Cl', 'C[C@](Cl)(Br)I'),
 ('I[C@](Br)(C)Cl', 'C[C@@](Cl)(Br)I'),
 ('C[C@](Br)(I)Cl', 'C[C@](Cl)(Br)I'),
 ('C[C@@](Br)(I)Cl', 'C[C@@](Cl)(Br)I'),
 ('C[C@](I)(Cl)Br', 'C[C@](Cl)(Br)I'),
 ('C[C@@](I)(Cl)Br', 'C[C@@](Cl)(Br)I'),
 ('Cl[C@@](I)(C)Br', 'C[C@](Cl)(Br)I'),
 ('Cl[C@](I)(C)Br', 'C[C@@](Cl)(Br)I'),
 ('Br[C@](I)(C)Cl', 'C[C@](Cl)(Br)I'),
 ('Br[C@@](I)(C)Cl', 'C[C@@](Cl)(Br)I'),
 ('Cl[C@](Br)(C)I', 'C[C@](Cl)(Br)I'),
 ('Cl[C@@](Br)(C)I', 'C[C@@](Cl)(Br)I'),
 ('Br[C@@](Cl)(C)I', 'C[C@](Cl)(Br)I'),
 ('Br[C@](Cl)(C)I', 'C[C@@](Cl)(Br)I'),
 ('Br[C@@](I)(Cl)C', 'C[C@](Cl)(Br)I'),
 ('Br[C@](I)(Cl)C', 'C[C@@](Cl)(Br)I'),
 ('Br[C@](Cl)(I)C', 'C[C@](Cl)(Br)I'),
 ('Br[C@@](Cl)(I)C', 'C[C@@](Cl)(Br)I')]
        for smi, cansmi in smi_and_cansmi:
            mol = pybel.readstring("smi", smi)
            self.assertEqual(mol.write("can").split()[0],
                             cansmi)
